artifacts_root: artifacts

file_data_path: data/
language: vi

use_async: False
show_progress: False

vector_store_query_mode: default
store_nodes_override: False
insert_batch_size: 128
similarity_top_k: 2

defaults:
  - embedding: cross
  - splitter: sentence
  - vector_store: milvus
  - reraank: cohere